### ISSUE TITLE
Temporal Pyramid

### ISSUE THREAD

**Issue by jingmouZhong** [Trunpm/TPT-for-VideoQA#1]
Thanks for you great works! In your code, the appearance feature dimension is (batch_size, levels, 16, 2048). If the level is setting as n, the total segments is ![](http://latex.codecogs.com/svg.latex?2^{n}-1), is it meaning the dimension levels is ![](http://latex.codecogs.com/svg.latex?2^{n}-1)? Did you compare the condition about random sample the same number of segments as temporal pyramid.
Thanks.

**Comment by Trunpm** [comment]
I didn't try it, I think it's hard to keep the scalability between video features with random sampling. But it can be tried. @jamzhong1
